modLoader = "javafml"
loaderVersion = "[4,)"
license = "BSD 3"
issueTrackerURL = "https://github.com/yorkeJohn/TFC-Better-Blast-Furnace/issues"

[[mods]]
modId = "tfcbetterbf"
version = "${version}"
displayName = "TFC Better Blast Furnace"
logoFile = ""
authors = "tadashi_3"
description = '''A TerraFirmaCraft addon that adds a more compact way to insulate your blast furnace.'''

[[mixins]]
config = "tfcbetterbf.mixins.json"

[[dependencies.tfcbetterbf]]
modId = "neoforge"
mandatory = true
versionRange = "[21.1,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.tfcbetterbf]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1,1.21.2)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.tfcbetterbf]]
modId = "tfc"
mandatory = true
versionRange = "[4,)"
ordering = "AFTER"
side = "BOTH"
