name: Build & Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Grant permission to Gradle
        run: chmod +x gradlew

      - name: Build mod
        run: ./gradlew build

      - name: Publish
        uses: Kir-Antipov/mc-publish@v3
        with:
          curseforge-id: 1046432
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          modrinth-id: tr715LZ4
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}